//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PulseAPK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PulseAPK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        public static string About_DevelopedBy {
            get {
                return ResourceManager.GetString("About_DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Page.
        /// </summary>
        public static string About_DeveloperPage {
            get {
                return ResourceManager.GetString("About_DeveloperPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Page.
        /// </summary>
        public static string About_ProjectPage {
            get {
                return ResourceManager.GetString("About_ProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apktool Path.
        /// </summary>
        public static string ApktoolPath {
            get {
                return ResourceManager.GetString("ApktoolPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ubersign Path.
        /// </summary>
        public static string UbersignPath {
            get {
                return ResourceManager.GetString("UbersignPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PulseAPK.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK file creation failed.
        /// </summary>
        public static string BuildFailed {
            get {
                return ResourceManager.GetString("BuildFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build &amp; Sign APK.
        /// </summary>
        public static string BuildHeader {
            get {
                return ResourceManager.GetString("BuildHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to APK file successfully created.
        /// </summary>
        public static string BuildSuccessful {
            get {
                return ResourceManager.GetString("BuildSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode Resources.
        /// </summary>
        public static string DecodeResources {
            get {
                return ResourceManager.GetString("DecodeResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode Sources.
        /// </summary>
        public static string DecodeSources {
            get {
                return ResourceManager.GetString("DecodeSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompile failed.
        /// </summary>
        public static string DecompileFailed {
            get {
                return ResourceManager.GetString("DecompileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompilation.
        /// </summary>
        public static string DecompileHeader {
            get {
                return ResourceManager.GetString("DecompileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompile successful.
        /// </summary>
        public static string DecompileSuccessful {
            get {
                return ResourceManager.GetString("DecompileSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Apktool: .
        /// </summary>
        public static string DownloadApktool {
            get {
                return ResourceManager.GetString("DownloadApktool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download JAVA: .
        /// </summary>
        public static string DownloadJava {
            get {
                return ResourceManager.GetString("DownloadJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop a file.
        /// </summary>
        public static string DragDropHint {
            get {
                return ResourceManager.GetString("DragDropHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop a folder.
        /// </summary>
        public static string DragDropFolderHint {
            get {
                return ResourceManager.GetString("DragDropFolderHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open folder: {0}.
        /// </summary>
        public static string Error_CouldNotOpenFolder {
            get {
                return ResourceManager.GetString("Error_CouldNotOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; does not exist..
        /// </summary>
        public static string Error_FolderNotFound {
            get {
                return ResourceManager.GetString("Error_FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid APK File.
        /// </summary>
        public static string Error_InvalidApkFile {
            get {
                return ResourceManager.GetString("Error_InvalidApkFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The apktool path &apos;{0}&apos; does not exist. Please update it in Settings..
        /// </summary>
        public static string Error_InvalidApktoolPath {
            get {
                return ResourceManager.GetString("Error_InvalidApktoolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Jar File.
        /// </summary>
        public static string Error_InvalidJarFile {
            get {
                return ResourceManager.GetString("Error_InvalidJarFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Ubersign File.
        /// </summary>
        public static string Error_InvalidUbersignFile {
            get {
                return ResourceManager.GetString("Error_InvalidUbersignFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Drop a valid project folder that contains apktool.yml and AndroidManifest.xml..
        /// </summary>
        public static string Error_InvalidProjectSelection {
            get {
                return ResourceManager.GetString("Error_InvalidProjectSelection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please configure the apktool path in Settings before running a decompile..
        /// </summary>
        public static string Error_MissingApktool {
            get {
                return ResourceManager.GetString("Error_MissingApktool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder is not set..
        /// </summary>
        public static string Error_OutputFolderNotSet {
            get {
                return ResourceManager.GetString("Error_OutputFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK Files (*.apk)|*.apk|All Files (*.*)|*.*.
        /// </summary>
        public static string FileFilter_Apk {
            get {
                return ResourceManager.GetString("FileFilter_Apk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jar Files (*.jar)|*.jar.
        /// </summary>
        public static string FileFilter_Jar {
            get {
                return ResourceManager.GetString("FileFilter_Jar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ubersign Jar Files (*.jar)|*.jar.
        /// </summary>
        public static string FileFilter_Ubersign {
            get {
                return ResourceManager.GetString("FileFilter_Ubersign", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JAVA Path: {0}.
        /// </summary>
        public static string JavaPathFound {
            get {
                return ResourceManager.GetString("JavaPathFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAVA Path: Not Found.
        /// </summary>
        public static string JavaPathNotFound {
            get {
                return ResourceManager.GetString("JavaPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Original Manifest.
        /// </summary>
        public static string KeepOriginalManifest {
            get {
                return ResourceManager.GetString("KeepOriginalManifest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extract to a folder where APK is located.
        /// </summary>
        public static string ExtractToApkFolder {
            get {
                return ResourceManager.GetString("ExtractToApkFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build APK.
        /// </summary>
        public static string MenuBuild {
            get {
                return ResourceManager.GetString("MenuBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompile.
        /// </summary>
        public static string MenuDecompile {
            get {
                return ResourceManager.GetString("MenuDecompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output APK Path.
        /// </summary>
        public static string OutputApkLabel {
            get {
                return ResourceManager.GetString("OutputApkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Decompile.
        /// </summary>
        public static string RunDecompile {
            get {
                return ResourceManager.GetString("RunDecompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Build.
        /// </summary>
        public static string RunBuild {
            get {
                return ResourceManager.GetString("RunBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select APK.
        /// </summary>
        public static string SelectApk {
            get {
                return ResourceManager.GetString("SelectApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Project Folder.
        /// </summary>
        public static string SelectProjectFolder {
            get {
                return ResourceManager.GetString("SelectProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting apktool....
        /// </summary>
        public static string StartingApktool {
            get {
                return ResourceManager.GetString("StartingApktool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for command....
        /// </summary>
        public static string WaitingForCommand {
            get {
                return ResourceManager.GetString("WaitingForCommand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign APK.
        /// </summary>
        public static string SignApk {
            get {
                return ResourceManager.GetString("SignApk", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use AAPT2.
        /// </summary>
        public static string UseAapt2 {
            get {
                return ResourceManager.GetString("UseAapt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder does not appear to be a valid apktool project (missing apktool.yml or AndroidManifest.xml).
        /// </summary>
        public static string Warning_InvalidProjectFolder {
            get {
                return ResourceManager.GetString("Warning_InvalidProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK Analyser.
        /// </summary>
        public static string MenuAnalyser {
            get {
                return ResourceManager.GetString("MenuAnalyser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK Analyser.
        /// </summary>
        public static string AnalyserHeader {
            get {
                return ResourceManager.GetString("AnalyserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Analysis.
        /// </summary>
        public static string RunAnalysis {
            get {
                return ResourceManager.GetString("RunAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting analysis....
        /// </summary>
        public static string AnalysisStarting {
            get {
                return ResourceManager.GetString("AnalysisStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis complete.
        /// </summary>
        public static string AnalysisComplete {
            get {
                return ResourceManager.GetString("AnalysisComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis failed.
        /// </summary>
        public static string AnalysisFailed {
            get {
                return ResourceManager.GetString("AnalysisFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root check: True.
        /// </summary>
        public static string RootCheckFound {
            get {
                return ResourceManager.GetString("RootCheckFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root check: False.
        /// </summary>
        public static string RootCheckNotFound {
            get {
                return ResourceManager.GetString("RootCheckNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulator check: True.
        /// </summary>
        public static string EmulatorCheckFound {
            get {
                return ResourceManager.GetString("EmulatorCheckFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulator check: False.
        /// </summary>
        public static string EmulatorCheckNotFound {
            get {
                return ResourceManager.GetString("EmulatorCheckNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcoded username/password: True.
        /// </summary>
        public static string CredentialsFound {
            get {
                return ResourceManager.GetString("CredentialsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcoded username/password: False.
        /// </summary>
        public static string CredentialsNotFound {
            get {
                return ResourceManager.GetString("CredentialsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL queries: True.
        /// </summary>
        public static string SqlQueriesFound {
            get {
                return ResourceManager.GetString("SqlQueriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL queries: False.
        /// </summary>
        public static string SqlQueriesNotFound {
            get {
                return ResourceManager.GetString("SqlQueriesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/HTTPS paths: True.
        /// </summary>
        public static string HttpUrlsFound {
            get {
                return ResourceManager.GetString("HttpUrlsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/HTTPS paths: False.
        /// </summary>
        public static string HttpUrlsNotFound {
            get {
                return ResourceManager.GetString("HttpUrlsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Found in:.
        /// </summary>
        public static string FoundIn {
            get {
                return ResourceManager.GetString("FoundIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder does not contain Smali files..
        /// </summary>
        public static string Error_InvalidSmaliProject {
            get {
                return ResourceManager.GetString("Error_InvalidSmaliProject", resourceCulture);
            }
        }
    }
}
